name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      sm_version:
        description: 'Version'
        required: true
        default: 'warning'
        type: choice
        options:
        - v2.0-oneclick
        - v2.0-oneclick-rc
        - prod
  push:
    branches:
      - main  # Replace with the branch name you want to trigger the workflow on

jobs:
  print-option:
    runs-on: ubuntu-latest

    steps:
    - name: Check if Manual Run
      run: |
        if [ -n "${{ github.event.inputs.sm_version }}" ]; then
          echo "This is a manual run."
          SELECTED_OPTION="${{ github.event.inputs.sm_version }}"
        else
          echo "This is a push event."
          SELECTED_OPTION="No option provided (push event)"
        fi
        echo "SELECTED_OPTION=${SELECTED_OPTION}" >> $GITHUB_ENV

    - name: Print Selected Option
      run: |
        echo "You selected: $SELECTED_OPTION"
